#    Model Creation

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, roc_curve, auc

In [20]:
df = pd.read_csv("/Users/sa10/Downloads/Financial Fraud Detection TLAB/Financial-Fraud-Detection/data/new_data.csv")

In [30]:
# Separate features and target
X = df.drop(columns=["isFraud"])
y = df["isFraud"]

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Logistic Regression with max_iter and a different solver
logreg = LogisticRegression(max_iter=500, solver='saga')
logreg.fit(X_train_scaled, y_train)

# Make predictions
predlog = logreg.predict(X_test_scaled)

# Evaluate the model's performance
from sklearn.metrics import accuracy_score, classification_report
print(f"Accuracy: {accuracy_score(y_test, predlog)}")
print("Classification Report:")
print(classification_report(y_test, predlog))



/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Accuracy: 0.9991112151912263
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.97      0.31      0.47      1620

    accuracy                           1.00   1272524
   macro avg       0.99      0.65      0.73   1272524
weighted avg       1.00      1.00      1.00   1272524



In [36]:
print(accuracy_score(y_test, predlog))
print(confusion_matrix(y_test, predlog))
print(classification_report(y_test, predlog))

0.9991112151912263
[[1270891      13]
 [   1118     502]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.97      0.31      0.47      1620

    accuracy                           1.00   1272524
   macro avg       0.99      0.65      0.73   1272524
weighted avg       1.00      1.00      1.00   1272524



In [41]:
# Train the Naive Bayes model
nb = GaussianNB()
nb.fit(X_train, y_train)

# Predict on the test set
yprednb = nb.predict(X_test)

# Evaluate the model
print("Accuracy Score:", accuracy_score(y_test, yprednb))
print("Confusion Matrix:")
print(confusion_matrix(y_test, yprednb))
print("Classification Report:")
print(classification_report(y_test, yprednb))

Accuracy Score: 0.9987269395311994
Confusion Matrix:
[[1270904       0]
 [   1620       0]]
Classification Report:


/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.00      0.00      0.00      1620

    accuracy                           1.00   1272524
   macro avg       0.50      0.50      0.50   1272524
weighted avg       1.00      1.00      1.00   1272524



/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [42]:

# Hyperparameter tuning for kNN
paramgrid = {'n_neighbors': [3, 5, 7, 9]}  # values to test
gridknn = GridSearchCV(KNeighborsClassifier(), paramgrid, cv=5, scoring='f1') 
gridknn.fit(X_train, y_train)  # Fits the model on training data with cross-validation

# Print best parameters (best k value)
print(f"Best k value: {gridknn.best_params_['n_neighbors']}")

# Train the kNN model with the best k value
knn = KNeighborsClassifier(n_neighbors=gridknn.best_params_['n_neighbors'])
knn.fit(X_train, y_train)

# Predict using the trained model
ypredknn = knn.predict(X_test)

# Evaluate the model performance
print("Accuracy Score:", accuracy_score(y_test, ypredknn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, ypredknn))
print("Classification Report:")
print(classification_report(y_test, ypredknn))

Best k value: 5
Accuracy Score: 0.9992825282666574
Confusion Matrix:
[[1270865      39]
 [    874     746]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.95      0.46      0.62      1620

    accuracy                           1.00   1272524
   macro avg       0.97      0.73      0.81   1272524
weighted avg       1.00      1.00      1.00   1272524

